name: CI/CD for Helloworld Python App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker build -t my-python-app:latest .

      - name: Push image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUBTOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag my-python-app ghcr.io/$GITHUB_ACTOR/my-python-app:latest
          docker push ghcr.io/$GITHUB_ACTOR/my-python-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Minikube
        run: |
          minikube start
          minikube image load my-python-app:latest
          kubectl apply -f deployment-definition.yaml
          kubectl apply -f service-defintion.yaml