name: CI/CD for Helloworld Python App
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker build -t my-python-app:latest .

      - name: Push image to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUBTOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker tag my-python-app ghcr.io/$GITHUB_ACTOR/my-python-app:latest
          docker push ghcr.io/$GITHUB_ACTOR/my-python-app:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Start Minikube and Set Context
        run: |
          minikube status || minikube start
          kubectl config use-context minikube

      - name: Verify Minikube Status
        run: |
          kubectl cluster-info

      - name: Deploy to Minikube
        run: |
          minikube image load my-python-app:latest
          kubectl apply -f deployment-definition.yaml
          kubectl apply -f service-definition.yaml

      - name: Ensure deployment is rolled out
        run: |
          kubectl rollout status deployment/helloworld
          if [ $? -ne 0 ]; then
            echo "Deployment failed to roll out!"
            exit 1
          fi

      - name: Fetch Pod Logs for Debugging
        if: failure() # Run this step only if the previous step fails
        run: |
          kubectl get pods -l app=helloworld-app -o name | xargs -I {} kubectl logs {}

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Start Minikube and Set Context
        run: |
          minikube status || minikube start
          kubectl config use-context minikube
          
      - name: Wait for deployment to be ready
        run: |
          kubectl wait --for=condition=available --timeout=60s deployment/helloworld

      - name: Verify deployment, service and pods are running
        run: |
          kubectl rollout status deployment/helloworld
          kubectl get service helloworld-app-service -o wide
          kubectl get pods -l app=helloworld-app -o wide

      - name: Verify Kubernetes Pods are Running
        run: |
          POD_STATUS=$(kubectl get pods -l app=helloworld-app -o jsonpath='{.items[0].status.phase}')
          if [[ "$POD_STATUS" != "Running" ]]; then
            echo "ERROR: Pod is not running!"
            exit 1
          fi
          echo "✅ Pod is running."

      - name: Validate Logs Contain Expected Output
        run: |
          LOG_OUTPUT=$(kubectl logs -l app=helloworld-app --tail=10)
          if ! echo "$LOG_OUTPUT" | grep -q "Hello, World!"; then
            echo "ERROR: Expected log message not found!"
            exit 1
          fi
          echo "✅ Log output verified."
